WARNING 2024-07-29 08:50:01,489 views get datasources
WARNING 2024-07-29 08:50:06,465 views get datasources
WARNING 2024-07-30 06:49:22,234 views get datasources
WARNING 2024-07-30 07:30:10,475 views get datasources
WARNING 2024-07-30 07:30:23,058 views get datasources
WARNING 2024-07-30 07:46:39,232 views get datasources
{"levelname": "WARNING", "asctime": "2024-07-30 07:58:19,179", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources"}
{"levelname": "WARNING", "asctime": "2024-07-30 08:04:53,336", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources"}
{"levelname": "ERROR", "asctime": "2024-07-30 08:22:01,644", "module": "utils", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "utils.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/utils.py", "lineno": 161, "message": "No enabled LLM configuration found.", "exc_info": "Traceback (most recent call last):\n  File \"/Users/sachin/dev/terno-ai/terno/terno/llm/base.py\", line 32, in create_llm\n    config = LLMConfiguration.objects.get(enabled=True)\n  File \"/Users/sachin/opt/anaconda3/envs/terno/lib/python3.10/site-packages/django/db/models/manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/Users/sachin/opt/anaconda3/envs/terno/lib/python3.10/site-packages/django/db/models/query.py\", line 649, in get\n    raise self.model.DoesNotExist(\nterno.models.LLMConfiguration.DoesNotExist: LLMConfiguration matching query does not exist.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/sachin/dev/terno-ai/terno/terno/utils.py\", line 158, in llm_response\n    llm = LLMFactory.create_llm()\n  File \"/Users/sachin/dev/terno-ai/terno/terno/llm/base.py\", line 34, in create_llm\n    raise ValueError(\"No enabled LLM configuration found.\")\nValueError: No enabled LLM configuration found."}
{"levelname": "WARNING", "asctime": "2024-07-30 09:19:34,379", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources"}
{"levelname": "WARNING", "asctime": "2024-07-30 09:32:23,394", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources"}
{"levelname": "WARNING", "asctime": "2024-07-30 09:35:28,637", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources", "exc_info": null}
{"levelname": "WARNING", "asctime": "2024-07-30 09:35:33,353", "module": "views", "clientip": null, "sessionid": null, "username": null, "hostname": "Sachins-Air", "filename": "views.py", "pathname": "/Users/sachin/dev/terno-ai/terno/terno/views.py", "lineno": 40, "message": "get datasources", "exc_info": null}
